services:
  - type: web
    name: ml-disease-api
    env: python
    runtime: python-3.10.11
    buildCommand: ""
    startCommand: python app.py
    plan: free
    branch: main
    envVars:
      - key: FLASK_ENV
        value: production
